In [36]:
import pandas as pd

from statsmodels.tsa.arima.model import ARIMA

df = pd.read_csv('test.csv', index_col=0)

for_cr = df.select_dtypes('int64','float64')

for_cr

      iso3numeric  year  sovereign
1             760  2001          1
2             826  1941          1
3             608  1989          1
4             417  1944          0
5             132  1988          1
...           ...   ...        ...
4961          886  1961          0
4962          100  1986          1
4963          886  1995          0
4964          688  1987          0
4965          203  2005          1

[4965 rows x 3 columns]